// LOCALHOST

// GET
### Returns a default message - no data.
GET http://localhost:8080/ HTTP/1.1


### Returns all contacts in DB.
GET http://localhost:8080/contacts HTTP/1.1

### Returns a single document: Mike Lewis
GET http://localhost:8080/contacts/650f75b50809019a9a2fb6fe HTTP/1.1


// POST
### Add a new document to the collection.
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Sammy",
    "lastName": "Lewis",
    "email": "sammy@email.com",
    "favoriteColor": "Blonde",
    "birthday": "April 16"
}

// PUT
### Update a specific document: Change Melanie's e-mail and fav. color. 
PUT http://localhost:8080/contacts/650f75b50809019a9a2fb700 HTTP/1.1
content-type: application/json

{
    "firstName": "Melanie",
    "lastName": "Lewis",
    "email": "traingirl@email.com",
    "favoriteColor": "Sapphire",
    "birthday": "June 26"
}

// DELETE
### Delete a specific document: Remove Sammy (the family dog) 
### from the collection.
DELETE http://localhost:8080/contacts/65189af1be4362bd2b0a275e HTTP/1.1
content-type: application/json
